### ISSUE TITLE
Default -targetroot arg to same as -d arg

### ISSUE THREAD

**Issue by Arthurm1** [sourcegraph/lsif-java#130]
Is it possible to default the `-targetroot` arg to whatever is specified as the classfile destination dir (i.e. `-d` arg) when the `-targetroot` arg is not supplied?

It would make it easier to add the plugin to a [Bloop](https://github.com/scalacenter/bloop) target's javac options as currently the `-targetroot` would have to be transformed to handle each client's different classes directory.

The Scala semanticdb plugin does this but I didn't know if javacoptions are available to a Java plugin.

**Comment by olafurpg** [comment]
Thank you for reporting! The Java compiler API doesn't expose the `-d` flag from what I have seen. Even if we could access the flag, I would be on the fence about using it because I don't like defaulting to `-d` like semanticdb-scalac does. The default behavior in semanticdb-scalac has caused a lot of issues and my experience is that the explicit behavior in semanticdb-javac has resulted in fewer cryptic debugging sessions tracking down where the SemanticDB files got generated.

Important sidenote, semanticdb-javac doesn't clean up the generated SemanticDB files unlike semanticdb-scalac. In hindsight, I regret adding cleanup logic in semanticdb-scalac because it's really the responsibility of the build tool to do this.

For Bloop, I think it would make sense to have built-in support to enable SemanticDB similar to how it already has custom support for semanticdb-scalac. It should be easy to add the `-targetroot` flag from Bloop and also implement the necessary cleanup logic (delete SemanticDB files for deleted Java files).

Closing this issue as a wontfix.

**Comment by Arthurm1** [comment]
No worries.  I worked out where to add the targetroot in the Bloop code - I just didn't understand at first because Bloop manages so many different classes out dirs.

Thanks for the heads up about clean-up.  I haven't had a chance to work on the integration for a while but hoping to get back to it soon.  I still have a few issues to iron out but it was highlighting code nicely in Metals.  Except for when I had tabs instead of spaces, then it was well off - I haven't raised an issue as I wasn't sure whether this was metals or the plugin - I don't normally use tabs in code.
