### ISSUE TITLE
Render signatures for externally defined symbols

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#174]
Currently, hover messages only render signatures for symbols that are defined within the repository. The compiler plugin has all of the information to emit `SymbolInformation` for externally defined symbols as well so it would be nice if we added support for that as.

**Comment by Strum355** [comment]
For just rendering signatures, this should be relatively trivial. The awkward part comes from also extracting the javadoc. 

If we decide to get the javadoc via the source jars, I have previous work that was functional for the job (albeit with a non-zero amount of hacks due to 1) my inexperience at the time and 2) the unfortunate reliance on non-stable-guaranteed APIs.

Aside from that, performance took a nose dive (runtimes more than doubled iirc) once I implemented that, so I would be very much _for_ doing this processing on a separate thread/thread pool if that functionality is permitted by the compiler API.

**Comment by olafurpg** [comment]
I think we can separately deliver external signatures and docstrings. Signatures are more helpful IMO (but I suspect other people disagree) and they're easier to implement. The big question is whether external signatures should be emitted by semanticdb-javac or if they should be loaded on-demand during SemanticDB->LSIF conversion.

I think it would be ideal if we can do it on-demand. There is an API called "metacp" from the Scalameta repo that reads signatures directly from classfiles without a compiler. Alternatively, maybe we can somehow use semanticdb-javac APIs as a library during LSIF generation 🤔

**Comment by olafurpg** [comment]
For javadocs, we can build on top of the new `ClasspathEntry.sources` field here https://github.com/sourcegraph/lsif-java/blob/04287b3d3bad99e1dffc0c6c623b4a3f284f1c76/lsif-java/src/main/scala/com/sourcegraph/lsif_java/buildtools/ClasspathEntry.scala#L19

It's currently `None` most of the time but that can be fixed with small changes to the Maven/Gradle integrations.

I suspect performance will degrade if we use the javaparser library but we should first confirm with benchmarks before eliminating that route. The Metals repo has an API called "mtags" that already loads docstrings on-demand that we can use. The benefit of mtags and metacp is that they also support Scala.

**Comment by olafurpg** [comment]
@Strum355 given that https://github.com/sourcegraph/sourcegraph/issues/21057 has been fixed, what do you think about closing this issue with "wontfix"? Once we have cross-repo navigation, the hover message will anyways include the signature

**Comment by Strum355** [comment]
Yea that seems reasonable to me :+1:
