### ISSUE TITLE
Allow for `targetroot` to be based off the `javac` directory output

### ISSUE THREAD

**Issue by wiwa** [sourcegraph/lsif-java#219]
For Pants use it would be helpful to be able to output to a `META-INF` under whatever is passed to `zinc`/`javac`'s output dir (`-d` option).
 
 I played around with a solution in this commit: https://github.com/wiwa/lsif-java/commit/64f7195af92eadf84eaebd1b3f188eb52443efbf 

Not sure if this is how one is supposed to get `javac` options though...

**Comment by olafurpg** [comment]
Thank you for reporting! I am OK with merging that diff so that the targetroot can be automatically configured from the javac output directory. I think it would good to require the user to explicitly enable this behavior with something like `-targeroot:javac-classes-directory`. The targetroot wasn't auto-configurable because I didn't figure out how to extract the default compile directory from the compiler APIs 😅

**Comment by olafurpg** [comment]
The fix has been released as part of https://github.com/sourcegraph/lsif-java/releases/tag/v0.5.3
