### ISSUE TITLE
variable declaration and assignment

### ISSUE THREAD

**Issue by Kelvin-Lee** [sourcegraph/lsif-java#397]
`lsif-java` version: `0.7.2`

**Type of code:** assignment operator

**Expected behavior:** After defining a variable, assignment of a value afterwards should have precise code intelligence referencing the variable definition

**Actual behavior:** After defining a variable, assignment of a value afterwards does not have precise code intelligence referencing the variable definition

```
var blah = Set("abc")
blah = Set.empty[String]
```

**Comment by olafurpg** [comment]
Thank you for reporting! I'm able to reproduce. This issue is related to #396. In both siutations, multiple symbols are generated at the same location. The Scala language server solves this problem by falling back to known symbols that are related. For lsif-java, we need a different solution to handle cross-repo navigation.
